### ISSUE TITLE
Solution Update capabilities 

### ISSUE THREAD

**Issue by igomaa** [Azure/GuardrailsSolutionAccelerator#115]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mbrat2005** [comment]
Updated setup process includes this functionality, pulling in the work Jose had previously done on updating. Documentation needs to be updated

To update an existing deployment:
Import-Module src\GuardrailsSolutionAcceleratorSetup
    .EXAMPLE
        Update an existing GSA instance (PowerShell modules, workbooks, and runbooks):
        Deploy-GuardrailsSolutionAccelerator -configFilePath "C:\config.json" -updateComponents All

**Comment by mbrat2005** [comment]
See: https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/docs/update.md
