### ISSUE TITLE
Alerts on alerts on root/master accounts to detect a potential compromise

### ISSUE THREAD

**Issue by igomaa** [Azure/GuardrailsSolutionAccelerator#137]
according to TBS GitHub for GR1 , we are missing 
Configure appropriate alerts on root/master accounts to detect a potential compromise, in accordance with the [GC Event Logging Guidance](https://www.gcpedia.gc.ca/gcwiki/images/e/e3/GC_Event_Logging_Strategy.pdf)

can we please create a monitor to notify the compliance manager  about logging attempts from the break glass account 

Thanks 
Islam

**Comment by xuhongl** [comment]
After discussion, the target of this is to check whether the alerts exist
