### ISSUE TITLE
ReleaseVersion Tag should not be used in the logic or at least validated.

### ISSUE THREAD

**Issue by Rioux1010** [Azure/GuardrailsSolutionAccelerator#159]
**Is your feature request related to a problem? Please describe.**
I have spent some time investigating why automation account deployment was crashing to realize that i had overridden the tag ReleaseVersion while adding my organization's required tags.

**Describe the solution you'd like**

- You should avoid using the ReleaseVersion tag inside your code logic or make it clear that it is a required tag for your application to properly work 

- Add a validation on the presence of that tag in your code before using it. (https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/setup/setup.ps1#L488)

- A version file or a clear config value should be used

**Comment by igomaa** [comment]
Thanks for the feedback , we will add it to the docs

**Comment by igomaa** [comment]
I have updated the docs : https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/docs/setup.md#adding-tags-to-the-resource-group
Thanks
