### ISSUE TITLE
GuardRails 10 does not evaluate properly AAD settings on LAW

### ISSUE THREAD

**Issue by Rioux1010** [Azure/GuardrailsSolutionAccelerator#160]
**Describe the bug**
GuardRails 10 does not evaluate properly AAD settings to LAW

https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/src/GUARDRAIL%2011%20LOGGING%20AND%20MONITORING/Audit/Check-LoggingAndMonitoring.psm1#L167

**Expected behavior**
Evaluate properly

**Screenshots**
![image](https://user-images.githubusercontent.com/114452616/192568154-af40e471-7953-47b2-b868-c1dc92469f31.png)

![image](https://user-images.githubusercontent.com/114452616/192569868-37377724-7b78-455e-83be-fc740ffc32b7.png)

**Comment by igomaa** [comment]
can you please elaborate more

**Comment by Rioux1010** [comment]
Our AAD settings is properly configure with signinlogs and auditlogs and it is sent to our LAW. The Guardrail does not evaluate it properly. I have pasted the exact line of code in problem in the initial post.

**Comment by josefehse** [comment]
Thank you for pointing that out. found the issue and it will be fixed and released soon.
