### ISSUE TITLE
Guardrail 11 (ITSG AC2(12)) should exclude "CloudPosture" from evaluation of Standard Pricing

### ISSUE THREAD

**Issue by Rioux1010** [Azure/GuardrailsSolutionAccelerator#165]
**Describe the bug**
Right now, guardrail 11 ITSG Control AC2(12) will always return non compliant status because Cloud Security Posture Management (CloudPosture) feature is always considered free and can't be changed to a standard pricing.

Line of code where the problem is : 
https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/src/GUARDRAIL%2011%20LOGGING%20AND%20MONITORING/Audit/Check-LoggingAndMonitoring.psm1#L301

**Expected behavior**
Exclude  "CloudPosture" from evaluation

**Screenshots**
![image](https://user-images.githubusercontent.com/114452616/192884247-62ca86b7-0d73-4ccc-824b-7c08b52a60ae.png)

![image](https://user-images.githubusercontent.com/114452616/192884047-d78606c5-92fe-4386-970b-acbdf895c962.png)

![image](https://user-images.githubusercontent.com/114452616/192885332-3d9a5752-9993-41f0-ac21-f90642fee966.png)

**Comment by igomaa** [comment]
Hello, 
can you please PR for this, with the suggested fix

**Comment by Rioux1010** [comment]
Created the PR : #166
