### ISSUE TITLE
Guardrail 4: Code Pointing to an Old Indicator?

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#168]
**Describe the bug**
Currently cannot determine whether AppID has been installed for SSC Cloud Brokering Service Reporting. Code is searching for User account "SSC-CBS-Reporting@" + DepartmentNumber + "gc.onmicrosoft.com" but now the AppID instructions create an app registration called "SSC-CBS-Reporting-PrivateMarketplace"

**Software versions used:**
1.0.4

**Comment by igomaa** [comment]
closing the  the issue as it is duplicate of #199
