### ISSUE TITLE
Guardrail 11 - ITSG AU2 : "WorkSpace not configured to ingest activity Logs" evaluation does not work

### ISSUE THREAD

**Issue by Rioux1010** [Azure/GuardrailsSolutionAccelerator#173]
**Describe the bug**

The command `$ActivityLogDS=Get-AzOperationalInsightsDataSource -Workspace $LAW -Kind AzureActivityLog` is always returning $null.

Line in problem : https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/src/GUARDRAIL%2011%20LOGGING%20AND%20MONITORING/Audit/Check-LoggingAndMonitoring.psm1#L137

**Expected behavior**
I don't know what is the intent of the evaluation in that context. You are already evaluating  for proper configuration of Azure AD  "AuditLogs" and "SignInLogs" just a few lines below (line 168). 

If you want to check for proper Azure Activity Logs, i think you should either : 
- Loop through all subscriptions and check activity logs configuration
- and/or
- Check the existence of the Azure Activity table with the command Get-AzOperationalInsightsTable

If you want to check for proper AAD Logs, since you already checking proper AAD Diags settings config, i think you should :
- Check the existence of the Azure Activity table with the command Get-AzOperationalInsightsTable

**Screenshots**
![image](https://user-images.githubusercontent.com/114452616/193471256-9b2ec0dd-aac3-4303-ae5f-ac88373f7141.png)

![image](https://user-images.githubusercontent.com/114452616/193471717-dc6e170c-bd2c-441e-b552-2b96a974e8d0.png)

![image](https://user-images.githubusercontent.com/114452616/193471776-45939965-6048-4828-bc46-dc0a21d859e7.png)

![image](https://user-images.githubusercontent.com/114452616/193472010-69998b2a-e628-4021-8154-e1af2f6ba83e.png)

**Comment by josefehse** [comment]
Thank you for the feedback. I am investigating. I have a workspace that reports data using the command above but may be an old solution/configuration. Will check on how to proper determine Activity Logs presence.
![image](https://user-images.githubusercontent.com/13967863/195923387-b89d410d-fe8a-4ba4-a4f5-fc482d00d31c.png)

**Comment by josefehse** [comment]
Module has been updated to use the updated detection method.
