### ISSUE TITLE
GR 2: Notification of Guest User Error

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#180]
**Describe the bug**
Not clear what the error is trying to indicate as our environment does not have any external users or guest accounts.

![image](https://user-images.githubusercontent.com/111992749/194138694-d9a98324-7a97-4812-b6c8-f15c1d7adc4f.png)

**To Reproduce**
1. Go to workbook
2. Click on Guardrail 2
3. Scroll down to bottom of page

**Expected behavior**
Should not be receiving the error.

**Comment by josefehse** [comment]
For now , the table that collects the external users, if any, is never created if no users are found. The query therefore fails.
