### ISSUE TITLE
Improve config.json consistency and formatting 

### ISSUE THREAD

**Issue by mbrat2005** [Azure/GuardrailsSolutionAccelerator#201]
The current config.json file and included parameters are inconsistently named and do not reflect their purpose. Further, the file is difficult to generate correctly without referencing documentation. 

Proposed changes:
 - Move to a 'jsonc' format which allows inline comments to guide users--this requires PowerShell 7 on the host running the setup
 - Clarify parameter names, adding 'Prefix' to resource naming parameters
 - Consider adding a 'uniqueNameSuffix' parameter as an alternative to current tenant ID part
 - Follow consistent camelCasing

**Comment by igomaa** [comment]
@mbrat2005 , it is a great idea , however it has a impact on the setup process, I am going to close the Issue , and later we can discuss that later
