### ISSUE TITLE
Missing results for GR6 and GR7 (-ReportTime parameter appears to be missing according to the logs)

### ISSUE THREAD

**Issue by ElementUser** [Azure/GuardrailsSolutionAccelerator#237]
**Describe the bug**

After setting up the Guardrails Accelerator within our Azure environment, we are unable to get the Runbook results for GR6 and GR7:
![image](https://user-images.githubusercontent.com/15804376/204619235-ed1dd24d-8a29-4195-82d8-5c50690bcdad.png)

The error we encounter when looking through the corresponding Log Analytics Workspace (from the `GuardrailsComplianceException_CL` log table) is generally the following for each of the scripts that correspond to those GRs (I replaced sensitive information with `<REDACTED>`, and the example shown is for GR7):

> Failed invoke the module execution script for module 'Check-ProtectionOfDataInTransit', script 'Verify-ProtectionDataInTransit -ControlName System.Collections.Hashtable.CtrName7 -ItemName System.Collections.Hashtable.dataInTransit -PolicyID @{cbssubscriptionName=<REDACTED>; pbmmpolicyID=/providers/Microsoft.Authorization/policySetDefinitions/<REDACTED>; itsgcode=SC8}.pbmmpolicyID -MsgTable System.Collections.Hashtable -LogType GuardrailsCompliance -WorkSpaceID <REDACTED> -WorkspaceKey *** -ReportTime 2022-11-29 13:43:15 -CBSSubscriptionName @{cbssubscriptionName=<REDACTED>; pbmmpolicyID=/providers/Microsoft.Authorization/policySetDefinitions/<REDACTED>; itsgcode=SC8}.cbssubscriptionName -itsgcode @{cbssubscriptionName=<REDACTED>; pbmmpolicyID=/providers/Microsoft.Authorization/policySetDefinitions/<REDACTED>; itsgcode=SC8}.itsgcode'
with error: Exception calling "Invoke" with "0" argument(s): "Cannot process command because of one or more missing mandatory parameters: ReportTime."

However, if you look closely at the error message, you clearly see a `-ReportTime` flag with its corresponding arguments.

What is even more strange is that the other GuardRails use the same `-ReportTime` flag & arguments in the exact same way, yet we do not see this error occurring. Is this a common issue that others encounter when running the Guardrails Accelerator in their Azure environment?

**To Reproduce**

1. Set up the GuardRails Accelerator project properly on our Azure environment, then run it
2. Check the corresponding Runbook. There will be no results for GR6 and GR7
3. Check the corresponding Log Analytics Workspace in the `GuardrailsComplianceException_CL` log table. You should see the error messages I described earlier in the post

**Expected behavior**

We should get the proper results for GR6 and GR7 in our Runbook results with no errors in the `GuardrailsComplianceException_CL` log table

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 107.0.1418.26 (64-bit)

**Software versions used:**
 - Azure CLI version: N/A
 - Azure Cloudshell version: 2.0.20221029 (obtained via the `lsb_release -a` command - let me know if more info is needed)
 - Azure Bicep version: 0.12.1 (e43d137c2d)

**Comment by igomaa** [comment]
hello @ElementUser , can you please connect with me , I would like to see this error in your environment, my email is Isgomaa@...
thanks
Islam

**Comment by ElementUser** [comment]
@igomaa sure thing, I'll contact you after the holidays. Thank you for responding to my issue & happy holidays!

**Comment by ElementUser** [comment]
This has been fixed in v1.0.7 & it no longer occurs after we re-deployed.

We did run into other errors with GR5 and GR11 & that is being addressed in this PR: https://github.com/Azure/GuardrailsSolutionAccelerator/pull/250
