### ISSUE TITLE
GR 9 - Allow for new soon to come new Vnet DDos SKU

### ISSUE THREAD

**Issue by josefehse** [Azure/GuardrailsSolutionAccelerator#241]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by igomaa** [comment]
@josefehse , this require changes for the module , the existing solution is adequate
