### ISSUE TITLE
$IsCompliant Module Variable Should Default to $false

### ISSUE THREAD

**Issue by mbrat2005** [Azure/GuardrailsSolutionAccelerator#248]
**Describe the bug**

The current module design declares $IsCompliant = $true at the start of the modules, and compliance state is set to $false based on test results. This is a less-safe design because a test that fails to execute correctly but doesn't properly error out could result in an incorrect compliance status. 

**Expected behavior**
Rewrite the modules so that $IsCompliant is false by default, then set to true when tests evaluate successfully.

**Comment by igomaa** [comment]
# keep open , until e verify all GRs
