### ISSUE TITLE
GR11 get-tenantDiagnosticsSettings 

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#254]
In Guardrail 11, for the function get-tenantDiagnosticsSettings 

function get-tenantDiagnosticsSettings {
    #$apiUrl=https://graph.microsoft.com/beta/auditLogs/directoryAudits
    $apiUrl = https://management.azure.com/providers/microsoft.aadiam/diagnosticSettings?api-version=2017-04-01-preview
    try {
        $Data = Invoke-AzRestMethod -Uri $apiUrl -Method Get
    }
    catch {
        Write-Error "Error: Failed to call Azure Resource Manager REST API at URL '$apiURL'; returned error message: $_"
    }
 
    return $data.value.properties
}

Return value $data.value.properties is empty

**To Reproduce**
1. Run the main runbook
2. Go to Guardrail 11 in the workbook
3. Even when everthing is complaint, it will display "Tenant Diagnostics settings are not pointing to the provided log analysitcs workspace."
4. Due to return being empty, it is never passing the compliance check for Tenant Diagnostics which checks if security log analysitcs workplace (LAW) is same as where AAD logs are being sent

**Expected behavior**
When Security LAW is matching the workspace where AAD diagnosticSettings are pointing - this compliance check needs to pass currently it is failing.

**Comment by igomaa** [comment]
duplicate issue https://github.com/Azure/GuardrailsSolutionAccelerator/issues/246
