### ISSUE TITLE
GR1: Break Glass Account Owners Contact information - Showing Compliant when no manager is listed

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#255]
**Describe the bug**
Breakglass accounts do not have manager property filled. However, it is showing as compliant in the workbook

**To Reproduce**
Create Breakglass accounts and leave manager property empty. Monitor the compliance state for the item in the workbook.

**Expected behavior**
If manager is not set, show not compliant. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8752276/210848006-229157aa-1f83-4843-80d3-9046ec5ac4da.png)
![image](https://user-images.githubusercontent.com/8752276/210848147-a2d598a0-98e8-4463-a65d-5f7bbd5932d0.png)

**Comment by mbrat2005** [comment]
Duplicate #243
