### ISSUE TITLE
GR1: Microsoft 365 E5 Assignment - Showing Not Compliant when AAD_PREMIUM_P2 licenses are already assigned to the BG Accounts

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#257]
**Describe the bug**
BG accounts showing not compliant when AAD_PREMIUM_P2 licenses are already assigned.

**To Reproduce**
Assign AAD P2 license to BG accounts
Monitor compliant state for the item name Microsoft 365 E5 Assignment

**Expected behavior**
AAD_PREMIUM_P2
EMSPREMIUM
ENTERPRISEPREMIUM
You can include more relevant ones, but above security oriented licenses should make this check compliant.

**Screenshots**
![image](https://user-images.githubusercontent.com/8752276/210849842-cf742c7a-73c1-4fb6-84dd-83f681154b87.png)

**Comment by mbrat2005** [comment]
Duplicate #254

**Comment by precog90** [comment]
Dupicate of #245 GR 1: Showing non-compliant when AAD_PREMIUM_V2 license is assigned to breakglass accounts #245
