### ISSUE TITLE
GSA instance update to v1.0.8 not working

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#264]
**Describe the bug**
As per Get-Help Deploy-GuardrailsSolutionAccelerator -Detailed

To update a GSA instance use this 
PS > # Update an existing GSA instance (PowerShell modules, workbooks, and runbooks):
Get-GSAExportedConfig -KeyVaultName guardrails-12345 | Deploy-GuardrailsSolutionAccelerator -update
    
But got this: 

PS /home/amrinder/v1.0.8/GuardrailsSolutionAccelerator-1.0.8> Get-GSAExportedConfig -KeyVaultName guardrails-a5f1fb10 | Deploy-GuardrailsSolutionAccelerator -update
Retrieving the latest configuration from Key Vault guardrails-a5f1fb10. To find a previous version, use the Azure Portal and browse the secret versions for secret name 'gsaConfigExportLatest'. Note that each secret version has tags with deployment details.
WARNING: Executing this command will output your config value to the console, which may be a security concern. It is recommended to run this command with the syntax below:

        Get-GSAExportedConfig -KeyVaultName guardrails-12345 | Remove-GSACoreComponents

Press ENTER to proceed or CTRL+C to cancel.

The command it is telling to execute does not exist

PS /home/amrinder/v1.0.8/GuardrailsSolutionAccelerator-1.0.8> Get-GSAExportedConfig -KeyVaultName guardrails-a5f1fb10 | Remove-GSACoreComponents
Remove-GSACoreComponents: The term 'Remove-GSACoreComponents' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**To Reproduce**
Install v1.0.7 version of the GSA and try to update to v1.0.8 

**Expected behavior**
GSA should update to the new version - updating PowerShell modules, workbooks, and runbooks

![image](https://user-images.githubusercontent.com/8752276/211106467-133432f3-c5a9-407d-bec0-083845ecce5b.png)

**Comment by mbrat2005** [comment]
@precog90, is your goal to update the deployed components or remove them? It looks like perhaps the help and info message for Get-GSAExportedConfig example should be tweaked to use a different example. 

To update using the previously exported config, you'd run the command as in your second attempt in the image above, and hit enter to pass the config from the Get-GSAExportedConfig to Deploy-GuardrailsSolutionAccelerator -update.

**Comment by precog90** [comment]
@mbrat2005  I was able to successfully update the version from 1.0.7 to 1.0.8. 

Remove-GSACoreComponents example was throwing me off. 

Please update the documentation as advised and you can close this off.
