### ISSUE TITLE
Deployment using the new released code still references old Module versions with the automation account

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#276]
Description: 

We installed the latest v1.0.8 version in our production environment expecting the latest code base. 

wget https://github.com/Azure/GuardrailsSolutionAccelerator/archive/refs/tags/v1.0.8.zip
Expand-Archive ./v1.0.8.zip
cd ./v1.0.8/GuardrailsSolutionAccelerator-1.0.8/setup/

![image](https://user-images.githubusercontent.com/8752276/214707216-c50aae56-7c11-442d-92a1-a30b3adb9265.png)

Even though v1.0.8 codebase has the new modules, modules loaded into the automation account are referencing previous versions. 

![image](https://user-images.githubusercontent.com/8752276/214707649-6469b0c2-033e-4bce-852e-1a89ff422533.png)

There are more but as per code base latest versions are:

![image](https://user-images.githubusercontent.com/8752276/214707803-ba234c36-d54a-456b-87da-2bc9f535c685.png)

v1.0.8 codebase referencing new version but not during the deployment:

![image](https://user-images.githubusercontent.com/8752276/214708099-9699f676-2e50-499d-b9e0-377df5c0ae27.png)

**Comment by mbrat2005** [comment]
WORKAROUND: Specify a release URL when installing or upgrading GSA. The default behavior references the 'main' branch, which can be inconsistent between releases. For exmaple:
```pwsh
Deploy-GuardrailsSolutionAccelerator -configFilePath ~\temp\config.json -alternatePSModulesURL https://github.com/Azure/GuardrailsSolutionAccelerator/raw/v1.0.8/psmodules
```

Suggested implementation for better consistency:
- Default to the latest release for install and upgrade operations. Use `Invoke-RestMethod https://api.github.com/repos/Azure/GuardrailsSolutionAccelerator/releases/latest` to get this information. Installation from the 'main' branch would occur only when explicitly specified via the -alternatePSModulesURL param
- This is not foolproof in that the release process contains manual steps which must be followed--investigate further automation
