### ISSUE TITLE
Mitigation URL not working on all the Guardrail

### ISSUE THREAD

**Issue by nadersip** [Azure/GuardrailsSolutionAccelerator#282]
**Describe the bug**

The links under the Mitigation section of all the guardrails are not directing us to the TBS Guardrails GitHub. We are receiving error 404 not found.

**To Reproduce**
1. Go to the workbook
2. Open the workbook
3. Chose any guardrails
4. Click on the GitHub link
5. See error

**Expected behavior**

When opening the URL we should by directed to the TBS Guardrails GitHub.

**Screenshots**
![image](https://user-images.githubusercontent.com/114234812/215186271-32011322-1a19-407e-8e29-bd601a7f0fdc.png)

![image](https://user-images.githubusercontent.com/114234812/215186491-2fc68d75-c859-4dcb-ba39-ac7f3003dfaa.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Microsoft Edge

**Comment by igomaa** [comment]
@nadersip , what are the recommendations here, should we point everything to SSC or TBS site , we are looking to redirect the link to a specific URL for each control ,  if you have a specific Link please add it here

**Comment by nadersip** [comment]
@igomaa We can redirect to the TBS Guardrails GitHub 
https://github.com/canada-ca/cloud-guardrails

gr-01: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/01_Protect-Root-Account.md
gr-02: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/02_Management-Admin-Privileges.md
gr-03: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/03_Cloud-Console-Access.md
gr-04 : https://github.com/canada-ca/cloud-guardrails/blob/master/EN/04_Enterprise-Monitoring-Accounts.md
gr-05: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/05_Data-Location.md
gr-06: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/06_Protect-Data-at-Rest.md
gr-07: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/07_Protect-Data-in-Transit.md
gr-08: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/08_Segmentation.md
gr-09: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/09_Network-Security-Services.md
gr-10: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/10_Cyber-Defense-Services.md
gr-11: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/11_Logging-and-Monitoring.md
gr-12: https://github.com/canada-ca/cloud-guardrails/blob/master/EN/12_Cloud-Marketplace-Config.md

**Comment by igomaa** [comment]
currently we generate the links dynamically , 

BaseURL + "/"+/#headerName

The new links will be in a json file stored into the GR storage account , the mitigation.json file will be ingested to the GR workspace on  pointed to the appropriate section in the Github repo 

-------------------------------------
Item Name | Mitigation Name | 
------------------------------------
Break Glass accounts Creation | https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/docs/controls.md#Break-Glass-accounts-Creation

**Comment by MathesonSho** [comment]
@igomaa could we complete the following suggestion you made to link dynamically to the controls document? https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/docs/controls.md

Item Name | Mitigation Name |
Break Glass accounts Creation | https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/docs/controls.md#Break-Glass-accounts-Creation
