### ISSUE TITLE
GR 8 & 9: "ExcludeFromCompliance" Tag used for GR 9 (DDoS Check) is also referenced in GR 8 for Subnet Compliance Check 

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#283]
**Describe the bug**
GR 8 & 9: "ExcludeFromCompliance" Tag used for GR 9 (DDoS Check) is also referenced in GR 8 for Subnet Compliance Check 

**To Reproduce**
1. Set ExcludeFromCompliance on VNet
2. Run the compliance runbook
3. This will exclude VNet from both GR 8 and GR 9 checks

**Expected behavior**
VNet Compliance will not be checked but Subnet Compliance should still be checked as they are part of two different guardrails. Also, VNet compliance looks for DDoS enabled - if that needs to be excluded but subnet based check might still be required. 
Maybe check for separate tags under each "ExcludeFromComplianceVNetDDoS" in GR9 and "ExcludeFromComplianceVNetSubnets" in GR8

Also, if any VNet is on exclusion list - can we ensure it becomes part of the compliant message. If no VNets, all are excluded -  message should be like - "Compliant but user are having these exclusions set-up"

![image](https://user-images.githubusercontent.com/8752276/215187596-f46ab9fd-f5cb-4be0-8aca-0948f96276a2.png)
![image](https://user-images.githubusercontent.com/8752276/215187848-6af275ac-558e-4052-a2f5-82365c8e4480.png)

**Comment by precog90** [comment]
Also please check if no VNets -  Compliant but no VNets found. Currently it is throwing an error:

![image](https://user-images.githubusercontent.com/8752276/215564966-e5784477-9b6a-4050-9da9-7def9978b3b3.png)

**Comment by josefehse** [comment]
For Guardrails 8, the tag for excluding the Vnet altogether will be:
"GR8-ExcludeVNetFromCompliance"
The tag containing a list of subnet names to be excluded (when applied to a Vnet) will be:
"GR-ExcludedSubnets"
For Guardrails 9, the tag for excluding the Vnet altogether will be:
"GR9-ExcludeVNetFromCompliance"
