### ISSUE TITLE
Document steps to update deployed configuration variables

### ISSUE THREAD

**Issue by mbrat2005** [Azure/GuardrailsSolutionAccelerator#296]
Extend the update documentation to include details on how to update configuration variables.

**Comment by precog90** [comment]
@mbrat2005 for updating the variable - just updating the keyvault secret did not work as I guess variable not fetched from there on every "main" runbook run. 
I had to update the variable in automation account and then for persistence reflect the same change in the key vault.. Just fyi - this is what I experienced.

**Comment by mbrat2005** [comment]
> @mbrat2005 for updating the variable - just updating the keyvault secret did not work as I guess variable not fetched from there on every "main" runbook run. I had to update the variable in automation account and then for persistence reflect the same change in the key vault.. Just fyi - this is what I experienced.

Thanks @precog90, this makes sense. We've debated moving all config variables to the Key Vault for retrieval at runtime, which would both simplify updating values in this scenario, and enable future scenarios that might move away from Azure Automation. I'll raise this with the team for consideration.
