### ISSUE TITLE
GR 5,6,7 broken after update to v1.0.9 

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#298]
**Describe the bug**
GR 5,6,7 broken after update to v1.0.9 

**To Reproduce**
Upgrade to v1.0.9

![image](https://user-images.githubusercontent.com/8752276/217115893-871422b4-503b-401d-aa2a-4119aa61e557.png)
![image](https://user-images.githubusercontent.com/8752276/217115921-5ec3f596-a727-45ca-973f-7a4f4516b6c3.png)
![image](https://user-images.githubusercontent.com/8752276/217115948-4b014cc3-4b78-477a-9ba8-eb27630975e5.png)

**Comment by mbrat2005** [comment]
See prerelease-v1.0.9.2 for fix: https://github.com/Azure/GuardrailsSolutionAccelerator/releases/tag/v1.0.9.1
