### ISSUE TITLE
Mandatory and Recommended Toggle v1.0.9

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#300]
![image](https://user-images.githubusercontent.com/111992749/217354487-679a882a-25bc-4acb-8392-a233ac0180d9.png)

**Comment by igomaa** [comment]
@MathesonSho , for GR5,6,7  that was impacted by  the workbook [bug  ](https://github.com/Azure/GuardrailsSolutionAccelerator/issues/298),  please test again and send us update

**Comment by MathesonSho** [comment]
![image](https://user-images.githubusercontent.com/111992749/217665155-d1ad4267-536e-434a-9088-98a8d2242912.png)

**Comment by mbrat2005** [comment]
- [ ] GR 1: Rename 'Break Glass Account Procedure (R)' to 'Break Glass Account Non-technical (R)'
- [ ] GR 1: Rename 'MFA Enforcement (M)' to 'MFA Enforcement Exclu. Break Glass Account (M)'
- [ ] GR 2: Add "Mandatory Control Suggestions"
- [ ] GR 2: Add "a recommended control"
- [ ] GR 3: Mandatory field is supposed to be an attestation field for 'Authorized Access (M)'
- [ ] GR 7: Missing recommendation to check for TLS 1.2
- [ ] GR 8: Inconsistent mandatory/optional between title and data; make mandatory in data 
- [ ] GR 9: Missing mandatory attestations and additional recommendations
- [ ] GR 10: Missing mandatory attestations 
- [ ] GR 11: Missing mandatory indicator and suggestion

**Comment by mbrat2005** [comment]
@MathesonSho: for GR 3, 'Authorized Access' "Mandatory field is supposed to be an attestation field"--we are already checking for PrivilegedAccountManagementPlan.txt (an attestation). I'm not sure what to change here...

**Comment by MathesonSho** [comment]
- [ ] GR2: Add "Privileged Account Management Plan" doc attestation - mandatory [Exists in GR3 already]
[ ] https://github.com/Azure/GuardrailsSolutionAccelerator/issues/197: Let me know if all this answers your question. 

- [ ]  GR 2: Add "Microsoft Defender for Cloud" - recommended [need more information on what is being evaluated - already checking for paid plans in GR 11 Check-DefenderForCloudConfig]
-  Correct. This has been absorbed into GR 11 and is complete.

- [ ]  GR 7: Add an attestation that TLS 1.2 is enabled [required?] wherever possible (attestation)
- https://github.com/Azure/GuardrailsSolutionAccelerator/issues/207 - please add at the minimum an attestation.  Eventually this needs to be an indicator field leading up to the stable release. 

- [ ]  GR 9: Missing "target network architecture" doc attestation mandatory [same as GR 8 'Target Network Architecture Diagram?]
- https://github.com/Azure/GuardrailsSolutionAccelerator/issues/211

- [ ] GR 11: Add missing control "Severity Notifications to a Primary Email" - mandatory [Defender email contact? What is a primary email?]
- notification being triggered to an email (GA email, generic email etc.,)- any email that the client chooses.
https://github.com/Azure/GuardrailsSolutionAccelerator/issues/214 

- [ ] GR 11: "Notifications enabled (user notifications for password changes and admin password notifications)" [We can't reliably check notification/alert configuration. Should this be an attestation?]
-  Yes. At the minimum we require an attestation. We are hoping to update this to an indicator field eventually.

**Comment by MathesonSho** [comment]
Guardrail 3: Authorized Access should have an attestation field that looks for the following document AuthorizedAccessProcessApprovedbyCSO.txt

Description: "TBS's key consideration of having an authorized user process approved by CSO or designated official for cyber security. Includes a risk-based conditional access control policy with appropriate logging and monitoring enabled."

**Comment by mbrat2005** [comment]
> Guardrail 3: Authorized Access should have an attestation field that looks for the following document AuthorizedAccessProcessApprovedbyCSO.txt
> 
> Description: "TBS's key consideration of having an authorized user process approved by CSO or designated official for cyber security. Includes a risk-based conditional access control policy with appropriate logging and monitoring enabled."

@MathesonSho The description above is a bit difficult to use in a Workbook--it ends up looking like this:
![image](https://user-images.githubusercontent.com/25390936/219668535-5d546e58-8655-4113-b087-91bcc090b400.png)

Is there a shorter description we can use?

**Comment by MathesonSho** [comment]
ItemName: Authorized Access
Comments: Could not find AuthorizedAccessProcessApprovedbyCSO.txt
