### ISSUE TITLE
Guardrail 11 - Reads disabled subscriptions

### ISSUE THREAD

**Issue by Justyn-lee** [Azure/GuardrailsSolutionAccelerator#32]
**Describe the bug**
Currently our GR 11 is noncompliant due to a disabled subscription but the steps that are used to fix the subscription are incorrect.
The disabled guardrail cannot be reactivated to correct the issues.
![image](https://user-images.githubusercontent.com/103066905/169358080-62faa127-ddb5-4020-8787-cd702aaf2bf0.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**

**Software versions used:**
 - E.g. Azure CLI version [e.g. v2.23.0]
 - Azure Bicep version [e.g. v0.4.613]

**Additional context**

**Comment by igomaa** [comment]
hello @Justyn-lee , the issue h as been fixed , can you please download module 11 and re-uploaded to the automation account .
thanks 
IG
