### ISSUE TITLE
Initialization: New .json Field Required

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#328]
**Is your feature request related to a problem? Please describe.**
In order to report tenant compliance to the TBS Guardrails the tool needs to collect the Profile level information from the client. Right now it does not have that information in the .json config file.

**Describe the solution you'd like**
Could we add this new .json field into the initialization of the solution?
Once completed this would need to be incorporated into the compliance reporting. 

**Profiles and Required Guardrails**
![image](https://user-images.githubusercontent.com/111992749/222557771-a985b8da-d0f6-43b2-aa2a-4992eaec446e.png)

**Comment by igomaa** [comment]
include in the config.json a new filed : profile {1}
the input will be saved in a Variable in the Autt Account 
data above will be always in the info tab , and collected by the CSPM

**Comment by igomaa** [comment]
1- Add additional entry in the setup.config  with default value 1 , the field supports multi[le value comma separated
2- The value will be saved in Automation account encrypted 
3- backend runbook collect this data to LA 
=========================================
in the workbook , display compliance according to the above requirements
=========================================

**Comment by MathesonSho** [comment]
Hi @igomaa, the .json field we would like to use is "CloudUsageProfiles".

**More Information**
This field would need to accept multiple values,(i.e., CloudUsageProfiles = 1,2,6). A department could identify that their tenant has multiple profile levels within it. 

Once input, we only need the highest value to be used for evaluation.

**Comment by igomaa** [comment]
we
