### ISSUE TITLE
Policy exclusion for the scan.

### ISSUE THREAD

**Issue by mlala3** [Azure/GuardrailsSolutionAccelerator#34]
**Is your feature request related to a problem? Please describe.**
We need to be able to exclude subscription like CSB 

**Describe the solution you'd like**
Require to exclude subscriptions or resources such as CBS Cyber Defense Subscriptions from policy. 

**Describe alternatives you've considered**

**Additional context**

**Comment by josefehse** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** Require to exclude subscriptions or resources such as CBS Cyber Defense Subscriptions from policy.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Hello, could you be more specific on which control and kind of exemptions would you require?
