### ISSUE TITLE
GR 5,6,7 and main runbook errors due to missing Management, Security Resource Provider on the subscription

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#346]
**Describe the bug**
If the subscription does not have Management/Security resource provider registered, GR 5,6,7 will fail with below error:

cbssubscriptionName -itsgcode @{cbssubscriptionName=N/A; pbmmpolicyID=/providers/Microsoft.Authorization/policySetDefinitions/4c4a5f27-de81-430b-b4e5-9cbd50595a87; itsgcode=SA9(5)}.itsgcode' with error: Exception calling "Invoke" with "0" argument(s): "Error: Failed to execute the 'Get-AzManagementGroup'command--verify your permissions and the installion of the Az.Resources module; returned error message: The client '215f7d63-771f-4bd1-b009-d0f58b531075' with object id '215f7d63-771f-4bd1-b009-d0f58b531075' does not have authorization to perform action 'Microsoft.Management/register/action' over scope '/subscriptions/250a39de-edcf-46e4-a494-5a59a495c57e'or the scope is invalid. 

**To Reproduce**
1. Unregister Management, Security Resource Provider
2. Monitor main run book for errors

**Expected behavior**
Register Resource Providers as solution is being deployed so that Guardrail checks can be performed without any issues:

Register-AzResourceProvider -ProviderNamespace Microsoft.Management
 
Register-AzResourceProvider -ProviderNamespace Microsoft.Security

**Comment by mbrat2005** [comment]
@precog90 Is the missing registration in the CBS subscription or the one where Guardrails is deployed?

**Comment by precog90** [comment]
@mbrat2005 the one where Guardrails is deployed

**Comment by mbrat2005** [comment]
Check for Microsoft.Security, Microsoft.Networking, Microsoft.Management resource providers.
