### ISSUE TITLE
GR4: AppID Additional Controls

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#351]
The current solution for GR4: AppID control uses the SPN's appid, then validates the correct permissions. We would also like to evaluate when the apps secret key has expired or not. 

**Mandatory Controls**
**Control 1:**  Validate the appid “exists” + has the correct permissions & role (GraphAPI, marketplace admin, etc…) (this has been implemented already)

**Control 2:** Validate whether the most recent secret key for that application has expired or not (report the expiration date as part of the log data)
-  Fail the control if the App expiry date is past the current date with the appropriate message

**Control 3:** attestation field for GR4 ensuring that appid + directoryid + secrektkey has been sent in an encrypted email to CSPM

Recommended Control
**Control 4:** Determine if there are multiple SecretKeys for the appid. If so, fail that control.

**Comment by igomaa** [comment]
@MathesonSho , APPID might have several secret, and often user give these secrets  random names, can you please list the scenarios ,  in case of the user has multiple secrets for the APPID  ,

**Comment by MathesonSho** [comment]
@igomaa, the AppID we are referring to has a standardized naming convention, unique appid, and has a single secret key.

**Comment by MathesonSho** [comment]
@igomaa see updated request based on feedback of users potentially having multiple secrets.

**Comment by MathesonSho** [comment]
@igomaa Note: Need to update the publicly facing documents on AppID and SPN as well.
