### ISSUE TITLE
Information tab in the GSA workbook does not work in v1.1.2

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#363]
**Describe the bug**
Information tab in the GSA workbook does not work  in v1.1.2

**To Reproduce**
Install the GSA version v1.1.2

![image](https://user-images.githubusercontent.com/8752276/230678947-42f63e07-e5ea-4a78-a4c2-67621cc6fec0.png)

**Comment by mbrat2005** [comment]
Confirmed in testing. The GR_VersionInfo_CL table appears to be empty, though the backend runbook executes. Need to debug

**Comment by mbrat2005** [comment]
![image](https://user-images.githubusercontent.com/25390936/232158629-cb195448-4968-4970-bcc6-3e6691cc08d3.png)

**Comment by mbrat2005** [comment]
![image](https://user-images.githubusercontent.com/25390936/232158726-1246e9cd-f695-45ad-be85-2b23d6495836.png)

**Comment by mbrat2005** [comment]
Possibly related to this change, which may migrate the table for DCRs? https://github.com/Azure/GuardrailsSolutionAccelerator/blob/main/setup/IaC/testAlert.bicep#L7

**Comment by mbrat2005** [comment]
The issue appears to be that when you pre-create a custom Log Analytics workspace table, it is created in the new version which only accepts data through the DCR/DCE model. We had pre-created the table to satisfy the query validation requirement of the Version Alert (scheduled query rule).

To work around the issue, we have disabled query validation on the scheduled query rule and are skipping pre-creating the VersionInfo table.

![image](https://user-images.githubusercontent.com/25390936/232580435-07df19c7-3af5-451e-b505-fe15d0fad8d8.png)

![image](https://user-images.githubusercontent.com/25390936/232581185-ef6a9e00-b3f6-4fc9-b634-5fef417232e0.png)
