### ISSUE TITLE
GR11: Error message not reflecting retention days set in the config.json file

### ISSUE THREAD

**Issue by precog90** [Azure/GuardrailsSolutionAccelerator#368]
**Describe the bug**
GR11: Error message not reflecting retention days set in the config.json file

**To Reproduce**
1. Set securityRetentionDays to 30 in config.json
2. Set Retention period for Security Log Analytics Workspace to 45 
3.  Observe the error in Azure Workbook

![image](https://user-images.githubusercontent.com/8752276/236338405-17dd9d72-e532-446e-8627-9e160b28c47d.png)

**Expected behavior**
Error needs to reflect the parameter passed in config.json file

**Comment by igomaa** [comment]
@josefehse , can you please update the the DOCS as well 
thanks
IG
