### ISSUE TITLE
20:BreakGlass Account Validation

### ISSUE THREAD

**Issue by igomaa** [Azure/GuardrailsSolutionAccelerator#370]
**Describe the bug**
ensure that both breakglass account are unique within the input of the json file 
module : Validate-BreakGlassAccount.psm1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**

**Software versions used:**
 - E.g. Azure CLI version [e.g. v2.23.0]
 - Azure Bicep version [e.g. v0.4.613]

**Additional context**

**Comment by mbrat2005** [comment]
Might as well do this in GuardrailsSolutionAccelerator\src\GuardrailsSolutionAcceleratorSetup\modules\Confirm-GSAConfigurationParameters\Confirm-GSAConfigurationParameters.psm1 as well
