### ISSUE TITLE
18:DepartmentList.csv lacks data integrity

### ISSUE THREAD

**Issue by igomaa** [Azure/GuardrailsSolutionAccelerator#371]
**Describe the bug**
review the document formatting for UTF-8  characters , 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**

**Software versions used:**
 - E.g. Azure CLI version [e.g. v2.23.0]
 - Azure Bicep version [e.g. v0.4.613]

**Additional context**

**Comment by MathesonSho** [comment]
@igomaa can this be removed?
