### ISSUE TITLE
GR5: Verify-AllowedLocation Module Execution Failing in the runbook

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#384]
**Describe the bug**
GR5: Verify-AllowedLocation Module Execution Failing in the runbook

**To Reproduce**
Install the latest version of GSA

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/ceb7d483-439c-487e-98c2-d73f1df1f211)

**Comment by mbrat2005** [comment]
@amrinderssc - is this installation from the latest tag, or 'main'?

**Comment by amrinderssc** [comment]
@mbrat2005 it was from the main
