### ISSUE TITLE
Upcoming Azure Storage Account change from public to private default and impact on the GSA solution

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#385]
**Describe the bug**
In August 2023, Azure is default all new storage accounts to private. As public endpoint is required for GSA functionality, please update the bicep template during provisioning to manually set to public.

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/d2dfec7a-cfcf-4707-8b8e-8a5b853de615)

**Comment by mbrat2005** [comment]
Neither of these settings changes apply to the Storage Account deployed with the GSA infrastructure. We do not allow public anonymous access (Automation Account access to storage uses the assigned MSI), and we are not doing anything with cross-tenant replication.
