### ISSUE TITLE
Check-DeprecatedAccounts.psm1 returning all disabled accounts as non-compliant

### ISSUE THREAD

**Issue by JoChampagne-BACLAC** [Azure/GuardrailsSolutionAccelerator#400]
**Describe the bug**
This module adds all Disabled users to the $DeprecatedUsers Array.

The reason for this is because Get-AzADUser lists the following default properties:'DisplayName', 'Id', 'DeletedDateTime', 'UserPrincipalName', 'UsageLocation', 'GivenName', 'SurName', 'AccountEnabled', 'MailNickName', 'Mail'. If you want to gather other non-default properties, you need to use Select.

So on line 21, "onPremisesSyncEnabled" will always return $null.

The Line should be:

Get-AzADUser -Filter "accountEnabled eq false" -Select OnPremisesSyncEnabled,UserPrincipalName | Where-Object {$null -eq $_.onPremisesSyncEnabled}

**Comment by mbrat2005** [comment]
Good catch @JoChampagne-BACLAC!
