### ISSUE TITLE
Runtime Errors due to Azure AD Free Subscription "Access To Azure Active Directory"

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#403]
**Describe the bug**
Due to the presence of "Access To Azure Active Directory" subscription on which clients have no access control permissions - GSA main runbook is failing with errors and GR5 results not reported. 

Details around the subscription: 

https://www.jasonfritts.me/2020/04/07/what-is-the-access-to-azure-active-directory-subscription-for/

**Expected behavior**
Skip the checks on this subscription if present

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/0e2ef6a7-ac02-439a-a814-7a42484a5fe1)

**Comment by amrinderssc** [comment]
@mbrat2005 Here are the properties of the the sub, maybe you can use one:  

Id                        : 482c2c11-b64b-453d-b094-ef48fc906f2b
Name                      : Access to Azure Active Directory
State                     : Enabled
SubscriptionId            : 482c2c11-b64b-453d-b094-ef48fc906f2b
TenantId                  :  XXXXXXXXXXXXXXXXXXX
HomeTenantId              : XXXXXXXXXXXXXXXXXXX
ManagedByTenantIds        : {}
CurrentStorageAccountName : 
SubscriptionPolicies      : {
                              "LocationPlacementId": "Public_2014-09-01",
                              "QuotaId": "AAD_2015-09-01",
                              "SpendingLimit": "On"
                            }
ExtendedProperties        : {[HomeTenant, XXXXXXXXXXXXXXXXXXX ], [AuthorizationSource, RoleBased], [Environment, AzureCloud], [Tenants, XXXXXXXXXXXXXXXXXXX]…}
CurrentStorageAccount     : 
AuthorizationSource       : RoleBased
Tags                      :

Maybe exact match on the Name property "Access to Azure Active Directory" ?

**Comment by igomaa** [comment]
@mbrat2005 , from.what I have seen the sub name doesn't change,  we  an filter by name and exclude that sub

**Comment by mbrat2005** [comment]
Right, but then you could rename a subscription and have it be excluded, right?
________________________________

**Comment by igomaa** [comment]
As far as I know these subs are read only you can't touch them rename them, the question is what happen if we have an agency has renamed one his landing zone sub that is hosting his ADs with.that name, we probably need another condition such subscription mode read-only or something , 
I have asked to.have a meeting with the customer to enumerate the sub properties for better filtering. 
What do you think

**Comment by mbrat2005** [comment]
You can change the subscription display name whenever you want, since it is not used as an identifier. I don't think these subscriptions appear any different that a new subscription, based on what Amrinder sent over.

I thought the general recommendation was to delete these subscriptions and that it is safe to do so, since there isn't a scenario where they would be used anymore.
________________________________

**Comment by amrinderssc** [comment]
@mbrat2005 We also need to figure out a plan for these alongside the above one: 

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/8e86a7c8-150c-4c4d-aa11-b57ea9ebabe8)

**Comment by mbrat2005** [comment]
Are you tagging at the subscription level? Maybe we could have an exclude subscription tag, like we do for VNETs—assuming the 'Access to Azure AD' subscriptions can be tagged...
________________________________

**Comment by josefehse** [comment]
@amrinderssc, could you confirm the QuotaId parameter for all the subs that are causing issues and they all have the same (and that no other has the same QuotaId of AAD_2015_09_01)?

**Comment by ashfenixx** [comment]
Workaround available.
