### ISSUE TITLE
Backend Runbook errors after merging PR# 402

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#404]
**Describe the bug**
Backend Runbook errors due after merging PR# 402

**To Reproduce**
1. Update the revisions as provided in PR# 402 
2.  Run the backend runbook to add new fields to the table and observe the error

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/419bc1ca-7137-45d7-b4a5-b1c9ba58be16)
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/f411675f-a930-4ed9-a59a-7870d7300e66)

**Comment by mbrat2005** [comment]
#422
