### ISSUE TITLE
GR11: Health and Security Monitoring Compliance status shows non compliant even though all the guardrails requirements are met

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#406]
**Describe the bug**
Health and Security Monitoring Compliance status shows false even though all the guardrails requirements are met.

**To Reproduce**
1. Install v1.1.4 
2. Remediate the guardrail requirements
3. Observe status of Health Monitoring and Security Monitoring Items 

**Expected behavior**
Health and Security Monitoring update to compliant status once guardrail requirements are met. 

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/f65784e4-62b0-4bbb-9ca1-4ab9fb2518b3)

**Comment by josefehse** [comment]
Should be fixed with #416
