### ISSUE TITLE
Microsoft.Storage RP registration error during installation if subscription is new

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#411]
**Describe the bug**
For a new subscription during the installation, installation threw an error that storage account name is not available because Microsoft.Storage RP was not registered. 

**To Reproduce**
1. Create a new subscription 
2. Install GSA

**Expected behavior**
Microsoft.Storage is enabled if not already on the subscription during the installation.

**Comment by mbrat2005** [comment]
@amrinderssc do you happen to have the error? Was it when checking name availability for the storage account?

**Comment by amrinderssc** [comment]
@mbrat2005  the error was around name availability but once Microsoft.Storage registered it was able to run through that
