### ISSUE TITLE
Validate size of key vault and storage account name in config.json that it does not exceed the limit as part of pre-requisites check 

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#412]
**Describe the bug**
As GSA adds another octet of the client Tenant ID at the end of the names, please validate config.json storage account and key vault are within the limits of 3-24 including the octet that will be added later as part of the pre-requisites check

**To Reproduce**
1. Set KV and Storage account name greater than 16 characters 
2. Observe the error

**Comment by mbrat2005** [comment]
See #398
