### ISSUE TITLE
GSA: Validate storage account and key vault are following the conventions as part of pre-requisites check of installation

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#413]
**Describe the bug**
Validate storage account and key vault are following the conventions as part of pre-requisites check of installation

KV: 
Key vault secret names have a limitation and only allows Alphanumerics and hyphens. Special characters such as “_” is not allowed in key vault secret names. 

Storage Account Name:
Storage account names must be between 3 and 24 characters in length and may contain numbers and lowercase letters only.
Your storage account name must be unique within Azure. No two storage accounts can have the same name.

**To Reproduce**
1. Create KV and Storage Account not following the guidelines
2. Observe the installation process

**Comment by mbrat2005** [comment]
see #398
