### ISSUE TITLE
Suspended Actions for Main Runbook

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#414]
**Describe the issue**
Solution runs the main runbook for 25 min before suspending the action and restarting 2 minutes later. This has caused results for Guardrails 10,11 and 12 to not appear in the workbook. 
**Backend Runbook**

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/d8787a68-d015-42ed-a48c-155fb618c88a)

**Main Runbook**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/0ff65ae1-1703-4dcf-805c-75d508d64d37)
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/e0babf97-dc01-40b9-9ce2-558593455120)
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/f843041a-1630-4554-b85c-235dd47dfaa1)

**Workbook**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/f4bd6e43-86e9-488c-a63c-732ce0081fa9)

How do we improve this or determine what is slowing the Main Runbook down?

**Comment by v-jsheehan** [comment]
The suspensions are likely related to the 400mb memory limit in place on [Azure Sandbox jobs](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#automation-limits)

Some of the common solutions to that issue are:

1) Move to using a [Hybrid Runbook worker](https://learn.microsoft.com/en-us/azure/automation/automation-hybrid-runbook-worker) which does not have the 400MB limit 

2) Remove any unnecessary modules from your Automation Account. When a sandbox is launched it loads every module from your automation account into its memory space to be ready to import them into your runbooks’ PowerShell sessions as needed. Removing unnecessary modules will reduce the memory footprint of every sandbox process. https://learn.microsoft.com/en-us/azure/automation/shared-resources/modules

3) Add in '[System.GC]::GetTotalMemory($true)' can be used to force a Garbage Collection and to report on the current memory usage which is useful for the runbook developer to track memory usage at different points in the runbook.

4) Using the appropriate filters to minimize the data returned when querying external data

**Comment by mbrat2005** [comment]
Testing move to ARG: https://github.com/mbrat2005/GuardrailsSolutionAccelerator/tree/vnet-complaince-arg

**Comment by mbrat2005** [comment]
@amrinderssc Are you able to run a test against the tenant with this issue? I refactored the modules in Guardrail 9 to use Azure Resource Graph, which we expect will cut down on memory consumption and execution time. The modules are here: https://github.com/mbrat2005/GuardrailsSolutionAccelerator/tree/vnet-complaince-arg/src/GUARDRAIL%209%20NETWORK%20SECURITY%20SERVICES/Audit

**Comment by ashfenixx** [comment]
Requires further testing on larger environments. Tagging as as Won't Fix for final pilot release on this repo.
