### ISSUE TITLE
GSA CentralView Storage Account Minimum TLSv1.2 and ftps state FTPSOnly as recommended by solution architecture review

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#434]
**Describe the bug**
GSA CentralView Storage Account Minimum TLSv1.2 and ftps state FTPSOnly as recommended by solution architecture review

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/7fde94e4-bfae-493e-8fd7-0ca16a5524af)

**Comment by josefehse** [comment]
FTP configuration is not required since Basic Auth for Publishing is disabled by default (and so is FTP or FTPs).
