### ISSUE TITLE
v1.1.5.1- Workbook is Incorrect

### ISSUE THREAD

**Issue by MathesonSho** [Azure/GuardrailsSolutionAccelerator#435]
**Describe the bug**
The release no longer uses the correct workbook for client deployment.

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/111992749/fb0462d6-7d41-48bc-a820-14291d4e9f29)

Bug seems to be introduced from this PR https://github.com/Azure/GuardrailsSolutionAccelerator/commit/d4d52e4752af70b8bae2b292d0fe1d3c306730f1

**To Reproduce**
1. Install v1.1.5.1
2. Go to workbook and see the Central View rather than the Guardrail Accelerator Workbook.

**Comment by josefehse** [comment]
Found the issue. Will test and submit a PR tomorrow morning.
