### ISSUE TITLE
main.ps1 erroring out since October 1 2023 with error Get-AzStorageAccount : Resource group 'xxxx' could not be found. for multiple client tenants

### ISSUE THREAD

**Issue by amrinderssc** [Azure/GuardrailsSolutionAccelerator#451]
**Describe the bug**
main.ps1 erroring out since October 1 with error Get-AzStorageAccount : Resource group 'xxxx' could not be found.

This is happening for multiple client tenants

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/133687120/7e4a14c3-72eb-4324-8e69-d9175b1d9abb)

**Additional context**
Happened to a set of client tenants  running different versions older and newer not every tenant

**Comment by singhgss** [comment]
So this is the line thats calling the GR-Common.ps1 to read blob storage content. 
It seems all we are doing in main.ps1 is checking the existing existing subscription 
So if a client has multiple subscriptions and when an account signs on that can access several subscriptions, any of those subscriptions may be added to the user's/runbook context
This explains why it occurs for some clients while works for others as for the ones its working they must have had their default subscription or current subscription set to the right one. 

![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/146129702/3af7512a-2ef4-461b-b561-f0a9f4f01069)

To fix it so is guaranteed that we always search the right storage account 

We should add this in main.ps1
```
# Ensures you do not inherit an AzContext in your runbook
Disable-AzContextAutosave -Scope Process

# Connect to Azure with system-assigned managed identity
$AzureContext = (Connect-AzAccount -Identity).context

# set and store context
$AzureContext = Set-AzContext -SubscriptionName $AzureContext.Subscription -DefaultProfile $AzureContext
```
source: https://learn.microsoft.com/en-us/azure/automation/context-switching
https://learn.microsoft.com/en-us/azure/automation/manage-runbooks

**Comment by TeamDman** [comment]
Was able to mitigate by adding `-SubscriptionId 5555-5555-5555-5555` to this line
https://github.com/Azure/GuardrailsSolutionAccelerator/blob/eecbf92f88b18553a2da60d6302b7eb0b8bf6e0a/setup/main.ps1#L34

**Comment by singhgss** [comment]
So the right thing to do is figure out the subscription id programatically and ensure runbooks Az Context is set to that. 
I think this solution will work 
The runtime config in guard rail keyvault should contain the correct subscription id which we can leverage in main.ps1 
```
$runtimeConfig = Get-AzKeyVaultSecret -VaultName $KeyVaultName -Name 'gsaConfigExportLatest' -AsPlainText -ErrorAction Stop | ConvertFrom-Json | Select-Object -Expand runtime
Set-AzContext -SubscriptionId $runtimeConfig.subscriptionId
```
