### ISSUE TITLE
Environment variable ENV:AZUREPS_HOST_ENVIRONMENT not detecting the Automation Account 

### ISSUE THREAD

**Issue by nadersip** [Azure/GuardrailsSolutionAccelerator#455]
**Describe the bug**

The runbook is not able to detect if it is being run from the Automation account. This is cause failures in the clients tenant.

**Expected behavior**
The runbook should be able to detect the host environment 

**Screenshots**
![image](https://github.com/Azure/GuardrailsSolutionAccelerator/assets/114234812/4ad6d3a8-94e4-455a-b2c3-c5345ffd2afd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**

**Software versions used:**
 - E.g. Azure CLI version [e.g. v2.23.0]
 - Azure Bicep version [e.g. v0.4.613]

**Additional context**

**Comment by singhgss** [comment]
Looks like this was fixed 3 hours ago by this commit 
https://github.com/Azure/GuardrailsSolutionAccelerator/commit/57f995d6bea8c6670a3799dc4d3baefcead818c7#diff-a506dc2b612c2890ef30c03c837af06d895b45675cd20cb54e3322159a4177baR13

Can we do the same for backend.ps1
In func Get-GSAAutomationVariable

`    If ($ENV:AZUREPS_HOST_ENVIRONMENT -eq 'AzureAutomation/') {
        $value = Get-AutomationVariable -Name $name
        return $value
    }
`

@TeamDman  @mbrat2005 
We will also need a critical release for this so our customers tenant can apply this.

**Comment by mbrat2005** [comment]
Sounds good—once the additional change to the backend runbook is in the PR, I'll approve and merge. Once merged, please submit another PR where you've updated the tags.json file release version to '1.1.7'. I'll merge the PR and publish the new release.
________________________________

**Comment by singhgss** [comment]
@mbrat2005  Raised PR for backend fix
