### ISSUE TITLE
Review and Adjust update script

### ISSUE THREAD

**Issue by josefehse** [Azure/GuardrailsSolutionAccelerator#81]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information if applicable):**

**Software versions used:**
 - E.g. Azure CLI version [e.g. v2.23.0]
 - Azure Bicep version [e.g. v0.4.613]

**Additional context**

**Comment by igomaa** [comment]
please refer to the new Setup redesign https://github.com/Azure/GuardrailsSolutionAccelerator/issues/192
